//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class B03_bind_view
    {
        public long id { get; set; }
        public Nullable<long> code_course { get; set; }
        public Nullable<long> serial_number_subject { get; set; }
        public string name_subject { get; set; }
        public string note { get; set; }
    }
}
