//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class B04_bind_view
    {
        public long id { get; set; }
        public long code_subject { get; set; }
        public string name_task { get; set; }
        public Nullable<long> equvivalent_perc { get; set; }
        public string note { get; set; }
    }
}
