//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T01_personalities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T01_personalities()
        {
            this.T02_tests = new HashSet<T02_tests>();
            this.T04_testing_tasks = new HashSet<T04_testing_tasks>();
            this.T05_test_passing_results = new HashSet<T05_test_passing_results>();
            this.T07_soundtracks = new HashSet<T07_soundtracks>();
        }
    
        public long id_person { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string date_birth { get; set; }
        public Nullable<long> gender { get; set; }
        public Nullable<long> code_category { get; set; }
        public Nullable<long> id_org { get; set; }
        public Nullable<long> code_class { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string date_updating { get; set; }
        public string note { get; set; }
    
        public virtual R01_people_category R01_people_category { get; set; }
        public virtual R02_pupils_classes R02_pupils_classes { get; set; }
        public virtual T10_organizations T10_organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T02_tests> T02_tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T04_testing_tasks> T04_testing_tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T05_test_passing_results> T05_test_passing_results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T07_soundtracks> T07_soundtracks { get; set; }
    }
}
