//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T02_view_tests
    {
        public long id_test { get; set; }
        public string name_test { get; set; }
        public string date_create { get; set; }
        public string date_correct { get; set; }
        public Nullable<long> max_passing_duration_sec { get; set; }
        public string note { get; set; }
    }
}
