//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T02_tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T02_tests()
        {
            this.B01_testing_aims_to_tests = new HashSet<B01_testing_aims_to_tests>();
            this.B05_testing_task_modules_to_tests = new HashSet<B05_testing_task_modules_to_tests>();
            this.T05_test_passing_results = new HashSet<T05_test_passing_results>();
        }
    
        public long id_test { get; set; }
        public string name_test { get; set; }
        public Nullable<long> id_method_material { get; set; }
        public Nullable<long> id_author { get; set; }
        public string date_create { get; set; }
        public string date_correct { get; set; }
        public Nullable<long> max_passing_duration_sec { get; set; }
        public string note { get; set; }
        public Nullable<long> id_teach_material { get; set; }
        public Nullable<long> max_count_TT_not_done_full_try { get; set; }
        public Nullable<long> max_count_TT_bcause_time_limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B01_testing_aims_to_tests> B01_testing_aims_to_tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B05_testing_task_modules_to_tests> B05_testing_task_modules_to_tests { get; set; }
        public virtual R07_methodical_materials R07_methodical_materials { get; set; }
        public virtual T01_personalities T01_personalities { get; set; }
        public virtual T06_teaching_materials T06_teaching_materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T05_test_passing_results> T05_test_passing_results { get; set; }
    }
}
