//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T03_view_tt_modules
    {
        public long id_module { get; set; }
        public string name_track { get; set; }
        public string name_av_track { get; set; }
        public string name_instruction { get; set; }
        public string name_variant { get; set; }
        public string name_play_result { get; set; }
        public Nullable<long> comment_view_duration_sec { get; set; }
        public Nullable<long> max_passing_duration_sec { get; set; }
        public string name_action { get; set; }
        public string description { get; set; }
        public string note { get; set; }
    }
}
