//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T04_testing_tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T04_testing_tasks()
        {
            this.B04_test_tasks_to_study_subjects = new HashSet<B04_test_tasks_to_study_subjects>();
            this.T03_testing_task_modules = new HashSet<T03_testing_task_modules>();
            this.T11_task_answers = new HashSet<T11_task_answers>();
        }
    
        public long id_task { get; set; }
        public string name_task { get; set; }
        public Nullable<long> id_author { get; set; }
        public string date_create { get; set; }
        public string date_correct { get; set; }
        public Nullable<long> code_type { get; set; }
        public string file_location { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B04_test_tasks_to_study_subjects> B04_test_tasks_to_study_subjects { get; set; }
        public virtual R03_testing_types R03_testing_types { get; set; }
        public virtual T01_personalities T01_personalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T03_testing_task_modules> T03_testing_task_modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T11_task_answers> T11_task_answers { get; set; }
    }
}
