//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T07_soundtracks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T07_soundtracks()
        {
            this.T03_testing_task_modules = new HashSet<T03_testing_task_modules>();
        }
    
        public long id_track { get; set; }
        public string name_track { get; set; }
        public Nullable<long> duration_sec { get; set; }
        public Nullable<long> id_announcer { get; set; }
        public string file_location { get; set; }
        public string note { get; set; }
    
        public virtual T01_personalities T01_personalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T03_testing_task_modules> T03_testing_task_modules { get; set; }
    }
}
