//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T07_view_soundtracks
    {
        public long id_track { get; set; }
        public string name_track { get; set; }
        public Nullable<long> duration_sec { get; set; }
        public string file_location { get; set; }
        public string note { get; set; }
    }
}
