//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T08_view_audio_video_tracks
    {
        public long id_av_track { get; set; }
        public string name_av_track { get; set; }
        public string name_type { get; set; }
        public string author { get; set; }
        public Nullable<long> duration_sec { get; set; }
        public string source { get; set; }
        public string image_size_pix { get; set; }
        public Nullable<long> filesize { get; set; }
        public string date_create { get; set; }
        public string note { get; set; }
    }
}
