//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oksana_kids
{
    using System;
    using System.Collections.Generic;
    
    public partial class T09_comment_variants_on_passing_tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T09_comment_variants_on_passing_tasks()
        {
            this.T03_testing_task_modules = new HashSet<T03_testing_task_modules>();
        }
    
        public long id_comment { get; set; }
        public Nullable<long> code_play_result { get; set; }
        public Nullable<long> is_av_track { get; set; }
        public string file_location { get; set; }
        public string note { get; set; }
    
        public virtual R13_play_result_variants R13_play_result_variants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T03_testing_task_modules> T03_testing_task_modules { get; set; }
    }
}
